/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.siagie.sttp.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Local service. Represents a row in the &quot;local_Local&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.siagie.sttp.model.impl.LocalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.siagie.sttp.model.impl.LocalImpl}.
 * </p>
 *
 * @author Diego
 * @see Local
 * @see com.siagie.sttp.model.impl.LocalImpl
 * @see com.siagie.sttp.model.impl.LocalModelImpl
 * @generated
 */
public interface LocalModel extends BaseModel<Local> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a local model instance should use the {@link Local} interface instead.
	 */

	/**
	 * Returns the primary key of this local.
	 *
	 * @return the primary key of this local
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this local.
	 *
	 * @param primaryKey the primary key of this local
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the local ID of this local.
	 *
	 * @return the local ID of this local
	 */
	public long getLocalId();

	/**
	 * Sets the local ID of this local.
	 *
	 * @param localId the local ID of this local
	 */
	public void setLocalId(long localId);

	/**
	 * Returns the nombre of this local.
	 *
	 * @return the nombre of this local
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this local.
	 *
	 * @param nombre the nombre of this local
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the estado of this local.
	 *
	 * @return the estado of this local
	 */
	public Integer getEstado();

	/**
	 * Sets the estado of this local.
	 *
	 * @param estado the estado of this local
	 */
	public void setEstado(Integer estado);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Local local);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Local> toCacheModel();

	@Override
	public Local toEscapedModel();

	@Override
	public Local toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}