/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pe.edu.aprolab.marco.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.AuditedModel;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the FamiliaProfesional service. Represents a row in the &quot;MARCO_FamiliaProfesional&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link pe.edu.aprolab.marco.model.impl.FamiliaProfesionalModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link pe.edu.aprolab.marco.model.impl.FamiliaProfesionalImpl}.
 * </p>
 *
 * @author Diego
 * @see FamiliaProfesional
 * @see pe.edu.aprolab.marco.model.impl.FamiliaProfesionalImpl
 * @see pe.edu.aprolab.marco.model.impl.FamiliaProfesionalModelImpl
 * @generated
 */
public interface FamiliaProfesionalModel extends AuditedModel,
	BaseModel<FamiliaProfesional> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a familia profesional model instance should use the {@link FamiliaProfesional} interface instead.
	 */

	/**
	 * Returns the primary key of this familia profesional.
	 *
	 * @return the primary key of this familia profesional
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this familia profesional.
	 *
	 * @param primaryKey the primary key of this familia profesional
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the familia profesional ID of this familia profesional.
	 *
	 * @return the familia profesional ID of this familia profesional
	 */
	public long getFamiliaProfesionalId();

	/**
	 * Sets the familia profesional ID of this familia profesional.
	 *
	 * @param familiaProfesionalId the familia profesional ID of this familia profesional
	 */
	public void setFamiliaProfesionalId(long familiaProfesionalId);

	/**
	 * Returns the company ID of this familia profesional.
	 *
	 * @return the company ID of this familia profesional
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this familia profesional.
	 *
	 * @param companyId the company ID of this familia profesional
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this familia profesional.
	 *
	 * @return the user ID of this familia profesional
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this familia profesional.
	 *
	 * @param userId the user ID of this familia profesional
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this familia profesional.
	 *
	 * @return the user uuid of this familia profesional
	 * @throws SystemException if a system exception occurred
	 */
	@Override
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this familia profesional.
	 *
	 * @param userUuid the user uuid of this familia profesional
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this familia profesional.
	 *
	 * @return the user name of this familia profesional
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this familia profesional.
	 *
	 * @param userName the user name of this familia profesional
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this familia profesional.
	 *
	 * @return the create date of this familia profesional
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this familia profesional.
	 *
	 * @param createDate the create date of this familia profesional
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this familia profesional.
	 *
	 * @return the modified date of this familia profesional
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this familia profesional.
	 *
	 * @param modifiedDate the modified date of this familia profesional
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the nombre of this familia profesional.
	 *
	 * @return the nombre of this familia profesional
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this familia profesional.
	 *
	 * @param nombre the nombre of this familia profesional
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the descripcion of this familia profesional.
	 *
	 * @return the descripcion of this familia profesional
	 */
	@AutoEscape
	public String getDescripcion();

	/**
	 * Sets the descripcion of this familia profesional.
	 *
	 * @param descripcion the descripcion of this familia profesional
	 */
	public void setDescripcion(String descripcion);

	/**
	 * Returns the sector of this familia profesional.
	 *
	 * @return the sector of this familia profesional
	 */
	public int getSector();

	/**
	 * Sets the sector of this familia profesional.
	 *
	 * @param sector the sector of this familia profesional
	 */
	public void setSector(int sector);

	/**
	 * Returns the estado of this familia profesional.
	 *
	 * @return the estado of this familia profesional
	 */
	public int getEstado();

	/**
	 * Sets the estado of this familia profesional.
	 *
	 * @param estado the estado of this familia profesional
	 */
	public void setEstado(int estado);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(FamiliaProfesional familiaProfesional);

	@Override
	public int hashCode();

	@Override
	public CacheModel<FamiliaProfesional> toCacheModel();

	@Override
	public FamiliaProfesional toEscapedModel();

	@Override
	public FamiliaProfesional toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}