/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pe.edu.aprolab.base.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the Formacion service. Represents a row in the &quot;BASE_Formacion&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link pe.edu.aprolab.base.model.impl.FormacionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link pe.edu.aprolab.base.model.impl.FormacionImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see Formacion
 * @see pe.edu.aprolab.base.model.impl.FormacionImpl
 * @see pe.edu.aprolab.base.model.impl.FormacionModelImpl
 * @generated
 */
public interface FormacionModel extends BaseModel<Formacion> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a formacion model instance should use the {@link Formacion} interface instead.
	 */

	/**
	 * Returns the primary key of this formacion.
	 *
	 * @return the primary key of this formacion
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this formacion.
	 *
	 * @param primaryKey the primary key of this formacion
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the formacion ID of this formacion.
	 *
	 * @return the formacion ID of this formacion
	 */
	public long getFormacionId();

	/**
	 * Sets the formacion ID of this formacion.
	 *
	 * @param formacionId the formacion ID of this formacion
	 */
	public void setFormacionId(long formacionId);

	/**
	 * Returns the company ID of this formacion.
	 *
	 * @return the company ID of this formacion
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this formacion.
	 *
	 * @param companyId the company ID of this formacion
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the nombre of this formacion.
	 *
	 * @return the nombre of this formacion
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this formacion.
	 *
	 * @param nombre the nombre of this formacion
	 */
	public void setNombre(String nombre);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Formacion formacion);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Formacion> toCacheModel();

	@Override
	public Formacion toEscapedModel();

	@Override
	public Formacion toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}