/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package pe.edu.aprolab.identidad.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Persona service. Represents a row in the &quot;ID_Persona&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link pe.edu.aprolab.identidad.model.impl.PersonaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link pe.edu.aprolab.identidad.model.impl.PersonaImpl}.
 * </p>
 *
 * @author Jorge Loayza Soloisolo
 * @see Persona
 * @see pe.edu.aprolab.identidad.model.impl.PersonaImpl
 * @see pe.edu.aprolab.identidad.model.impl.PersonaModelImpl
 * @generated
 */
public interface PersonaModel extends BaseModel<Persona> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persona model instance should use the {@link Persona} interface instead.
	 */

	/**
	 * Returns the primary key of this persona.
	 *
	 * @return the primary key of this persona
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persona.
	 *
	 * @param primaryKey the primary key of this persona
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the persona ID of this persona.
	 *
	 * @return the persona ID of this persona
	 */
	public long getPersonaId();

	/**
	 * Sets the persona ID of this persona.
	 *
	 * @param personaId the persona ID of this persona
	 */
	public void setPersonaId(long personaId);

	/**
	 * Returns the company ID of this persona.
	 *
	 * @return the company ID of this persona
	 */
	public long getCompanyId();

	/**
	 * Sets the company ID of this persona.
	 *
	 * @param companyId the company ID of this persona
	 */
	public void setCompanyId(long companyId);

	/**
	 * Returns the create date of this persona.
	 *
	 * @return the create date of this persona
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this persona.
	 *
	 * @param createDate the create date of this persona
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this persona.
	 *
	 * @return the modified date of this persona
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this persona.
	 *
	 * @param modifiedDate the modified date of this persona
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the codigo ID of this persona.
	 *
	 * @return the codigo ID of this persona
	 */
	@AutoEscape
	public String getCodigoId();

	/**
	 * Sets the codigo ID of this persona.
	 *
	 * @param codigoId the codigo ID of this persona
	 */
	public void setCodigoId(String codigoId);

	/**
	 * Returns the nombres of this persona.
	 *
	 * @return the nombres of this persona
	 */
	@AutoEscape
	public String getNombres();

	/**
	 * Sets the nombres of this persona.
	 *
	 * @param nombres the nombres of this persona
	 */
	public void setNombres(String nombres);

	/**
	 * Returns the apellido paterno of this persona.
	 *
	 * @return the apellido paterno of this persona
	 */
	@AutoEscape
	public String getApellidoPaterno();

	/**
	 * Sets the apellido paterno of this persona.
	 *
	 * @param apellidoPaterno the apellido paterno of this persona
	 */
	public void setApellidoPaterno(String apellidoPaterno);

	/**
	 * Returns the apellido materno of this persona.
	 *
	 * @return the apellido materno of this persona
	 */
	@AutoEscape
	public String getApellidoMaterno();

	/**
	 * Sets the apellido materno of this persona.
	 *
	 * @param apellidoMaterno the apellido materno of this persona
	 */
	public void setApellidoMaterno(String apellidoMaterno);

	/**
	 * Returns the genero of this persona.
	 *
	 * @return the genero of this persona
	 */
	public boolean getGenero();

	/**
	 * Returns <code>true</code> if this persona is genero.
	 *
	 * @return <code>true</code> if this persona is genero; <code>false</code> otherwise
	 */
	public boolean isGenero();

	/**
	 * Sets whether this persona is genero.
	 *
	 * @param genero the genero of this persona
	 */
	public void setGenero(boolean genero);

	/**
	 * Returns the estado civil of this persona.
	 *
	 * @return the estado civil of this persona
	 */
	public int getEstadoCivil();

	/**
	 * Sets the estado civil of this persona.
	 *
	 * @param estadoCivil the estado civil of this persona
	 */
	public void setEstadoCivil(int estadoCivil);

	/**
	 * Returns the fecha nacimiento of this persona.
	 *
	 * @return the fecha nacimiento of this persona
	 */
	public Date getFechaNacimiento();

	/**
	 * Sets the fecha nacimiento of this persona.
	 *
	 * @param fechaNacimiento the fecha nacimiento of this persona
	 */
	public void setFechaNacimiento(Date fechaNacimiento);

	/**
	 * Returns the ubigeo nacimiento of this persona.
	 *
	 * @return the ubigeo nacimiento of this persona
	 */
	@AutoEscape
	public String getUbigeoNacimiento();

	/**
	 * Sets the ubigeo nacimiento of this persona.
	 *
	 * @param ubigeoNacimiento the ubigeo nacimiento of this persona
	 */
	public void setUbigeoNacimiento(String ubigeoNacimiento);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Persona persona);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Persona> toCacheModel();

	@Override
	public Persona toEscapedModel();

	@Override
	public Persona toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}